// Shared between DiscoverScreen's fields filter and FieldsMapScreen's map
// filter so amenity tokens stay in sync with what OrganizationClaim.details
// (and the OSM importer's amenity mapping) actually stores.
export const paintballAmenities = [
  ["rentals", "Rental equipment"],
  ["beginner", "Beginner friendly"],
  ["low impact", "Low-impact paintball"],
  ["kids", "Youth programs"],
  ["air", "Air fills"],
  ["4500", "4500 PSI fills"],
  ["co2", "CO₂ fills"],
  ["pro shop", "On-site pro shop"],
  ["tech", "Tech services"],
  ["repair", "Repairs"],
  ["byop", "Bring your own paint"],
  ["paint included", "Paint included"],
  ["speedball", "Speedball field"],
  ["woodsball", "Woodsball field"],
  ["scenario", "Scenario field"],
  ["indoor", "Indoor play"],
  ["covered", "Covered staging"],
  ["lights", "Night play / lights"],
  ["chronograph", "Chronograph station"],
  ["turf", "Turf field"],
  ["food", "Food / concessions"],
  ["restrooms", "Restrooms"],
  ["parking", "Parking"],
  ["camping", "Camping"],
  ["showers", "Showers"],
  ["wifi", "Wi-Fi"],
  ["private parties", "Private parties"],
  ["corporate", "Corporate groups"],
  ["birthday", "Birthday packages"],
  ["league play", "League play"],
  ["tournaments", "Tournaments"],
  ["wheelchair", "Accessible facilities"],
  ["lodging", "Nearby lodging"],
  ["shipping", "Shipping"],
  ["online store", "Online store"],
  ["custom work", "Custom work"],
] as const;

// Mirrors backend OrganizationType — shared between DiscoverScreen's place
// filter and FieldsMapScreen's map type filter.
export const paintballPlaceTypes = [
  ["field", "Paintball field"],
  ["retailer", "Retailer / pro shop"],
  ["manufacturer", "Manufacturer"],
  ["airsmith", "Airsmith / tech"],
  ["hydro_testing", "Hydro testing"],
  ["event_producer", "Event producer"],
  ["league", "League / series"],
  ["media", "Paintball media"],
  ["photographer", "Photographer / video"],
  ["apparel", "Apparel / custom gear"],
  ["travel", "Travel / lodging"],
  ["training", "Training academy"],
  ["indoor_venue", "Indoor venue"],
  ["outdoor_venue", "Outdoor venue"],
  ["community", "Club / community"],
  ["other", "Other paintball business"],
] as const;
