import React,{useEffect,useState}from'react';import{ActivityIndicator,Image,Linking,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';import*as ImagePicker from'expo-image-picker';import{Alert}from'../utils/alert';import{communityService}from'../services/community.service';import{billingService}from'../services/billing.service';
export default function AddGearScreen({route,navigation}:any){const[name,setName]=useState('');const[category,setCategory]=useState('marker');const[manufacturer,setManufacturer]=useState('');const[model,setModel]=useState('');const[color,setColor]=useState('');const[condition,setCondition]=useState('good');const[notes,setNotes]=useState('');const[busy,setBusy]=useState(false);const[isPro,setIsPro]=useState(true);const[photos,setPhotos]=useState<string[]>([]);const[uploading,setUploading]=useState(false);
useEffect(()=>{billingService.getStatus().then(st=>setIsPro(st.isPro))},[]);
const upgrade=async()=>{try{const url=await billingService.startCheckout('monthly');await Linking.openURL(url)}catch{Alert.alert("Couldn't start checkout",'Please try again in a moment.')}};
const addPhoto=async()=>{if(!isPro){Alert.alert('Gear photos are a Pro feature','PBG Pro lets you attach photos to your gear items — $4/mo or $24/yr.',[{text:'Not now',style:'cancel'},{text:'Upgrade',onPress:upgrade}]);return}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:0.8});if(result.canceled)return;const asset=result.assets[0];setUploading(true);try{const{imageUrl}=await communityService.uploadGearPhoto(asset.uri,asset.mimeType);setPhotos(p=>[...p,imageUrl])}finally{setUploading(false)}};
const removePhoto=(url:string)=>setPhotos(p=>p.filter(x=>x!==url));
const save=async()=>{if(!name.trim())return Alert.alert('Name required','Give this item a recognizable name.');setBusy(true);try{await communityService.addGearItem(route.params.gearbagId,{name,category,manufacturer,model,color,condition,notes,images:photos.length?photos:undefined});Alert.alert('Gear added','The item is now in your digital gearbag.');navigation.goBack()}catch(e:any){Alert.alert('Could not add gear',e?.response?.data?.error?.message||'Please try again.')}finally{setBusy(false)}};
return<ScrollView style={s.page} contentContainerStyle={s.form}><Text style={s.kicker}>CATALOG EQUIPMENT</Text><Text style={s.title}>Add gear</Text><Text style={s.sub}>Private serial numbers stay private. Public details help other players understand your setup.</Text>{[['Item name',name,setName,'My primary marker'],['Category',category,setCategory,'marker'],['Manufacturer',manufacturer,setManufacturer,'Planet Eclipse'],['Model',model,setModel,'CS3'],['Color',color,setColor,'Graphite / Lime'],['Condition',condition,setCondition,'excellent'],['Notes',notes,setNotes,'Service history, upgrades, setup notes…']].map(([label,value,setter,placeholder]:any)=><React.Fragment key={label}><Text style={s.label}>{label}</Text><TextInput style={[s.input,label==='Notes'&&s.area]} value={value} onChangeText={setter} placeholder={placeholder} placeholderTextColor="#5e6972" multiline={label==='Notes'}/></React.Fragment>)}
<Text style={s.label}>Photos {!isPro&&<Text style={s.proTag}>PRO</Text>}</Text>
<View style={s.photoRow}>{photos.map(url=><View key={url} style={s.photoThumbWrap}><Image source={{uri:url}} style={s.photoThumb}/><Pressable style={s.photoRemove} onPress={()=>removePhoto(url)}><Text style={s.photoRemoveText}>×</Text></Pressable></View>)}<Pressable style={s.photoAdd} disabled={uploading} onPress={addPhoto}>{uploading?<ActivityIndicator color="#A8C84A"/>:<Text style={s.photoAddText}>+ Photo</Text>}</Pressable></View>
<Pressable style={s.save} disabled={busy} onPress={save}><Text style={s.saveText}>{busy?'Adding…':'Add to gearbag  →'}</Text></Pressable></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0A0E0F'},form:{width:'94%',maxWidth:720,alignSelf:'center',paddingTop:26,paddingBottom:70},kicker:{color:'#A8C84A',fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{color:'#fff',fontSize:34,fontWeight:'900',marginTop:7},sub:{color:'#84909a',lineHeight:21,marginTop:8,marginBottom:15},label:{color:'#c8d0d6',fontWeight:'800',marginTop:15,marginBottom:7},proTag:{color:'#A8C84A',fontSize:9,fontWeight:'900'},input:{backgroundColor:'#11161a',color:'#fff',borderWidth:1,borderColor:'#2d363d',borderRadius:12,padding:14},area:{minHeight:110,textAlignVertical:'top'},photoRow:{flexDirection:'row',flexWrap:'wrap',gap:10},photoThumbWrap:{width:84,height:84},photoThumb:{width:84,height:84,borderRadius:10,backgroundColor:'#11161a'},photoRemove:{position:'absolute',top:-6,right:-6,width:22,height:22,borderRadius:11,backgroundColor:'#1a2126',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#2d363d'},photoRemoveText:{color:'#fff',fontSize:14,lineHeight:16},photoAdd:{width:84,height:84,borderRadius:10,borderWidth:1,borderColor:'#2d363d',borderStyle:'dashed',alignItems:'center',justifyContent:'center'},photoAddText:{color:'#84909a',fontSize:11,fontWeight:'800'},save:{backgroundColor:'#A8C84A',padding:16,borderRadius:12,alignItems:'center',marginTop:24},saveText:{color:'#10150d',fontWeight:'900'}});
