import React,{useEffect,useState} from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { communityService,Gearbag } from '../services/community.service';
import { useTheme, DEFAULT_ACCENT } from '../store/ThemeContext';
export default function GearbagScreen({navigation}:any){const{accent}=useTheme();const[bags,setBags]=useState<Gearbag[]>([]);const[loading,setLoading]=useState(true);const[creating,setCreating]=useState(false);const[newName,setNewName]=useState('');const[submitting,setSubmitting]=useState(false);const load=()=>communityService.gearbags().then(setBags).finally(()=>setLoading(false));useEffect(()=>{void load()},[]);
const createBag=async()=>{if(!newName.trim())return;setSubmitting(true);try{await communityService.createGearbag({name:newName.trim()});setNewName('');setCreating(false);await load()}finally{setSubmitting(false)}};
const deleteBag=(b:Gearbag)=>Alert.alert('Delete this gearbag?',`"${b.name}" and its items will stop being tracked here.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await communityService.removeGearbag(b.id);await load()}}]);
if(loading)return <View style={s.center}><ActivityIndicator color={accent}/></View>;return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={[s.kicker,{color:accent}]}>DIGITAL GEARBAG</Text><Text style={s.title}>Your setup, dialed.</Text><Text style={s.sub}>Catalog equipment, track service, and turn any item into a marketplace listing.</Text>
<View style={s.newBagRow}>{creating?<View style={s.newBagForm}><TextInput style={s.newBagInput} value={newName} onChangeText={setNewName} placeholder="Gearbag name" placeholderTextColor="#65717a" autoFocus/><Pressable disabled={!newName.trim()||submitting} style={[s.add,{backgroundColor:accent},(!newName.trim()||submitting)&&{opacity:0.5}]} onPress={createBag}><Text style={s.addText}>{submitting?'Creating…':'Create'}</Text></Pressable><Pressable style={s.cancelBag} onPress={()=>{setCreating(false);setNewName('')}}><Text style={s.cancelBagText}>Cancel</Text></Pressable></View>:<Pressable style={s.newBagButton} onPress={()=>setCreating(true)}><Text style={[s.newBagButtonText,{color:accent}]}>+ New gearbag</Text></Pressable>}</View>
{!bags.length&&!creating&&<View style={s.empty}><Text style={s.emptyTitle}>No gearbags yet.</Text><Text style={s.emptyBody}>Create one to start cataloging your equipment.</Text></View>}
{bags.map(b=><View key={b.id}><View style={s.bagHead}><View><Text style={s.bagName}>{b.name}</Text><Text style={s.visibility}>{b.visibility.toUpperCase()} • {b.items.length} ITEMS</Text></View><View style={s.bagHeadActions}><Pressable style={[s.add,{backgroundColor:accent}]} onPress={()=>navigation.navigate('AddGear',{gearbagId:b.id})}><Text style={s.addText}>+ Add gear</Text></Pressable><Pressable style={s.deleteBag} onPress={()=>deleteBag(b)}><Text style={s.deleteBagText}>Delete</Text></Pressable></View></View><View style={s.grid}>{b.items.map(i=><View key={i.id} style={s.card}><View style={s.category}><Text style={[s.categoryText,{color:accent}]}>{i.category.toUpperCase()}</Text></View><Text style={s.itemName}>{i.name}</Text><Text style={s.model}>{[i.manufacturer,i.model].filter(Boolean).join(' ')}</Text><View style={s.rule}/><Text style={s.condition}>{i.condition||'Unrated'} {i.color?`• ${i.color}`:''}</Text>{i.serviceDueAt&&<Text style={s.service}>SERVICE DUE {new Date(i.serviceDueAt).toLocaleDateString()}</Text>}<View style={s.cardActions}><Pressable onPress={()=>navigation.navigate('GearItem',{item:i})}><Text style={s.link}>View details</Text></Pressable><Pressable onPress={()=>navigation.navigate('CreateListing',{gearItem:i})}><Text style={[s.sell,{color:accent}]}>Create listing →</Text></Pressable></View></View>)}</View></View>)}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0A0E0F'},content:{width:'94%',maxWidth:1100,alignSelf:'center',paddingTop:28,paddingBottom:90},center:{flex:1,backgroundColor:'#0A0E0F',alignItems:'center',justifyContent:'center'},kicker:{color:DEFAULT_ACCENT,fontSize:10,fontWeight:'900',letterSpacing:1.7},title:{color:'#fff',fontSize:38,fontWeight:'900',marginTop:8},sub:{color:'#89949d',fontSize:16,marginTop:8},newBagRow:{marginTop:20},newBagButton:{alignSelf:'flex-start',borderWidth:1,borderColor:'#2a3a2a',borderRadius:10,paddingHorizontal:14,paddingVertical:10},newBagButtonText:{fontWeight:'900',fontSize:12},newBagForm:{flexDirection:'row',alignItems:'center',gap:8},newBagInput:{flex:1,maxWidth:260,backgroundColor:'#121819',borderWidth:1,borderColor:'#273038',borderRadius:10,paddingHorizontal:12,paddingVertical:10,color:'#fff'},cancelBag:{paddingHorizontal:10,paddingVertical:11},cancelBagText:{color:'#75818a',fontWeight:'700'},empty:{alignItems:'center',paddingVertical:60},emptyTitle:{color:'#fff',fontSize:18,fontWeight:'900'},emptyBody:{color:'#7A8581',fontSize:12,marginTop:6},bagHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:30,marginBottom:14},bagHeadActions:{flexDirection:'row',alignItems:'center',gap:10},bagName:{color:'#fff',fontSize:22,fontWeight:'900'},visibility:{color:'#65717a',fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:5},add:{backgroundColor:DEFAULT_ACCENT,paddingHorizontal:15,paddingVertical:11,borderRadius:11},addText:{color:'#10150d',fontWeight:'900'},deleteBag:{paddingHorizontal:8,paddingVertical:11},deleteBagText:{color:'#E8743B',fontWeight:'800',fontSize:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:13},card:{backgroundColor:'#121819',borderWidth:1,borderColor:'#273038',borderRadius:18,padding:20,flexBasis:300,flexGrow:1,minHeight:220},category:{alignSelf:'flex-start',backgroundColor:'#1c281b',paddingHorizontal:9,paddingVertical:6,borderRadius:8},categoryText:{color:DEFAULT_ACCENT,fontSize:8,fontWeight:'900',letterSpacing:1},itemName:{color:'#fff',fontSize:20,fontWeight:'900',marginTop:18},model:{color:'#8e99a2',marginTop:5},rule:{height:1,backgroundColor:'#283037',marginVertical:16},condition:{color:'#aeb7bf',fontSize:12,textTransform:'capitalize'},service:{color:'#E8743B',fontSize:9,fontWeight:'900',marginTop:8},cardActions:{flexDirection:'row',justifyContent:'space-between',marginTop:'auto',paddingTop:18},link:{color:'#75818a',fontWeight:'700'},sell:{color:DEFAULT_ACCENT,fontWeight:'900'}});
